### PR TITLE
Add disable checkbox property

### PR DESCRIPTION
**Pull request by aloscha**

### CODE REVIEW

**Comment by mmnosek** [comment]
Just to clarify - is it connected with Sweoffshore Checklist Designer dropdown control?

**Comment by aloscha** [comment]
Indeed

**Comment by mmnosek** [comment]
I think that _disableCheckbox_ suggests that it is visible, but not able to change the value. May I ask you to change it for _checkboxHidden_ (false by default)?

**Comment by aloscha** [comment]
Fixed
`false by default` - bool is false by default, so if there no property we will get checkbox visible

**Pull request merged**
